openapi: 3.1.0

info:
  description: "An example for https://github.com/OpenAPITools/openapi-generator/issues/14599"
  title: Example Service API
  version: 0.0.1

components:
  responses:
    InternalServerError:
      description: "Error"
      headers:
        WWW_Authenticate:
          schema:
            type: string
  schemas:
    BasicObject:
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        type:
          $ref: '#/components/schemas/BasicObjectType'
    BasicObjectType:
      type: string
      enum:
        - Hello
        - World

paths:
  /basic/{id}:
    get:
      operationId: getBasic
      parameters:
        - in: path
          name: id
          required: true
          schema:
            format: integer
            type: int64
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicObject'
          description: Expected response to a valid request
        default:
          $ref: '#/components/responses/InternalServerError'
